# **Atividade 1 - Queimadas e doenças respiratorias em crianças na cidade de Marabá, Pará (2014-2016)**

## **1. Importação de Bibliotecas e Dados**

### 1.1 Importação de Bibliotecas

In [1]:
# Importando bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy.stats import pearsonr

# Imprimir informações
print("Bibliotecas importadas com sucesso!")

Bibliotecas importadas com sucesso!

### 1.2 Importação de Dados

In [2]:
# Caminho do Arquivo CSV
CAMINHO_ARQUIVO = r"..\data\DataBase.csv"
print("Caminho do arquivo csv definido!")

Caminho do arquivo csv definido!

In [3]:
# Criação do DataFrame inicial
df = pd.read_csv(CAMINHO_ARQUIVO, encoding='utf-8')
print("DataFrame inicial criado com sucesso!")

# Exibição do DataFrame inicial
print("\nExibindo as primeiras linhas do DataFrame:")
df.head()

DataFrame inicial criado com sucesso!

Exibindo as primeiras linhas do DataFrame:

,DataInicial,DataFinal,FocosDeQueimadas,Pneumonias,Asma,Bronquite,Bronquiolite,IVAS,Influenza,IRA,Sinusite
0,01/10/2016,31/12/2016,2138,37,0,1,0,0,0,0,0
1,01/07/2016,30/09/2016,2711,30,0,5,0,0,0,1,0
2,01/04/2016,30/06/2016,112,40,1,2,0,0,0,0,0
3,01/01/2016,31/03/2016,49,18,0,0,0,0,0,0,0
4,01/10/2015,31/12/2015,5034,19,0,2,0,0,0,0,0

## **2 Estrutura da Base de Dados**

### 2.1 Tipos de Dados

In [4]:
print("Exibindo os tipos de dados por colunas")
df.dtypes

Exibindo os tipos de dados por colunas

DataInicial           str
DataFinal             str
FocosDeQueimadas    int64
Pneumonias          int64
Asma                int64
Bronquite           int64
Bronquiolite        int64
IVAS                int64
Influenza           int64
IRA                 int64
Sinusite            int64
dtype: object

### 2.2 Estatísticas Descritivas

In [5]:
# Estatisticas Descritivas
print("Estatisicas Descritivas")
df.describe()

Estatisicas Descritivas

,FocosDeQueimadas,Pneumonias,Asma,Bronquite,Bronquiolite,IVAS,Influenza,IRA,Sinusite
count,12.0000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,1717.2500,36.916667,0.250000,1.166667,0.166667,0.833333,0.166667,0.166667,0.166667
std,2589.7128,14.500522,0.452267,1.403459,0.389249,1.267304,0.577350,0.389249,0.577350
min,5.0000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28.7500,27.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,297.5000,36.500000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2281.2500,43.250000,0.250000,1.250000,0.000000,1.250000,0.000000,0.000000,0.000000
max,8284.0000,65.000000,1.000000,5.000000,1.000000,4.000000,2.000000,1.000000,2.000000

## **3 Tratamento dos Dados**

### 3.1 Tratamento de tipos incorretos

In [6]:
# Conversão das colunas 'DataInicial' e 'DataFinal' para datetime
df['DataInicial'] = pd.to_datetime(df['DataInicial'], format='%d/%m/%Y')
print("Conversão da coluna 'DataInicial' para datetime feita com sucesso!")

df['DataFinal'] = pd.to_datetime(df['DataFinal'], format='%d/%m/%Y')
print("\nConversão da coluna 'DataFinal' para datetime feita com sucesso!")

Conversão da coluna 'DataInicial' para datetime feita com sucesso!

Conversão da coluna 'DataFinal' para datetime feita com sucesso!

### 3.2 Criação das colunas 'Total' e 'Média'

In [10]:
# Criação das colunas 'Total' e 'Média'
colunas_doencas = ['Pneumonias', 'Asma', 'Bronquite', 'Bronquiolite',
                   'IVAS', 'Influenza', 'IRA', 'Sinusite']
df['TotalIDR'] = df[colunas_doencas].sum(axis=1)
df['MediaIDR'] = df[colunas_doencas].mean(axis=1)

# Imprimir informações
print("Colunas 'Total' e 'Média' criadas com sucesso!")
df[['TotalIDR', 'MediaIDR']].head()

Colunas 'Total' e 'Média' criadas com sucesso!

   TotalIDR  MediaIDR
0        38     4.750
1        36     4.500
2        43     5.375
3        18     2.250
4        21     2.625

### 3.3 Criação de DataFrame Simplificado

In [12]:
# Criação de DataFrame Simplificado
df_simplificado = df[['DataInicial', 'DataFinal', 'FocosDeQueimadas', 'TotalIDR', 'MediaIDR']].copy()
print("DataFrame simplificado criado com sucesso!")

# Exibindo o DataFrame Simplificado
print("\nExibindo as cinco primeiras linhas do DataFrame simplificado")
df_simplificado.head()

DataFrame simplificado criado com sucesso!

Exibindo as cinco primeiras linhas do DataFrame simplificado

  DataInicial  DataFinal  FocosDeQueimadas  TotalIDR  MediaIDR
0  2016-10-01 2016-12-31              2138        38     4.750
1  2016-07-01 2016-09-30              2711        36     4.500
2  2016-04-01 2016-06-30               112        43     5.375
3  2016-01-01 2016-03-31                49        18     2.250
4  2015-10-01 2015-12-31              5034        21     2.625